### ISSUE TITLE
Remove link file libflatarray

### ISSUE THREAD

**Issue by egorpugin** [gentryx/libflatarray#16]
Hi,

Is it really necessary to keep this link inside src?
If library is header only maybe it's better to put all files under include/libflatarray/*.
It's more common layout.

Of course if you have good reasons, feel free to keep it as is.

**Comment by gentryx** [comment]
Good point. Fixed in 509b2b1f40693c71f99375457f0fe2bb0479e025 Thanks!

**Comment by egorpugin** [comment]
Just FYI.
I've added your library to C++ Archive Network.
https://cppan.org/pvt.cppan.demo.gentryx.libflatarray

It's under my service account in demo namespace.
Feel free to register there and add it yourself 'oficially' under your path (e.g. pvt.gentryx.libflatarray).

**Comment by gentryx** [comment]
@egorpugin Thanks for adding LibFlatArray there. Please report any build problems you might encounter.

Cheers!
-Andreas
