### ISSUE TITLE
missing libflatarray/config.h

### ISSUE THREAD

**Issue by cppljevans** [gentryx/libflatarray#19]
I've gotten following error:

/home/evansl/dwnlds/llvm/3.8/prebuilt/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang++ -I../github/libflatarray/include -DHAVE_LIBFLATARRAY -O0 -std=c++14 -o /tmp/build/clangxx3_8_pkg/clang/struct_of_arrays/work/soa_compare.benchmark.optim0.exe soa_compare.benchmark.cpp
In file included from soa_compare.benchmark.cpp:51:
In file included from ../github/libflatarray/include/libflatarray/flat_array.hpp:20:
In file included from ../github/libflatarray/include/libflatarray/estimate_optimum_short_vec_type.hpp:11:
In file included from ../github/libflatarray/include/libflatarray/detail/streaming_short_vec_switch.hpp:11:
In file included from ../github/libflatarray/include/libflatarray/short_vec.hpp:203:
../github/libflatarray/include/libflatarray/detail/short_vec_scalar_double_1.hpp:13:10: fatal error: 
      'libflatarray/config.h' file not found
#include <libflatarray/config.h>
         ^

Maybe you've not pushed it yet?

**Comment by gentryx** [comment]
@cppljevans The config.h should be created by cmake in your build directory. CMake will also create a Makefile that includes the corresponding directory in the include dirs.

Did you run CMake?

**Comment by cppljevans** [comment]
On 10/25/2016 06:06 AM, Larry Evans wrote:
>
>
> On 10/25/2016 05:59 AM, Andreas Schäfer wrote:
>> @cppljevans <https://github.com/cppljevans> The config.h should be
>> created by cmake in your build directory. CMake will also create a
>> Makefile that includes the corresponding directory in the include dirs.
>>
>> Did you run CMake?
>>
> No.  However, when I did, I got:
>
> ~/prog_dev/clang/struct_of_arrays/work $ cmake .
> -- The C compiler identification is GNU 5.4.0
> -- The CXX compiler identification is GNU 5.4.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> CMake Warning at CMakeLists.txt:3 (find_package):
>   By not providing "Findlibflatarray.cmake" in CMAKE_MODULE_PATH this
> project
>   has asked CMake to find a package configuration file provided by
>   "libflatarray", but CMake did not find one.
>
>   Could not find a package configuration file provided by "libflatarray"
> with
>   any of the following names:
>
>     libflatarrayConfig.cmake
>     libflatarray-config.cmake
>
>   Add the installation prefix of "libflatarray" to CMAKE_PREFIX_PATH or set
>   "libflatarray_DIR" to a directory containing one of the above files.  If
>   "libflatarray" provides a separate development package or SDK, be sure it
>   has been installed.
>
>
> -- Configuring done
> -- Generating done
> -- Build files have been written to:
> /home/evansl/prog_dev/clang/struct_of_arrays/work
> ~/prog_dev/clang/struct_of_arrays/work $
>
> I know little about cmake :(
>
> -regards,
> Larry
>
>
I guess you meant run cmake in the libflatarray directory?  I did that
but then got:

/home/evansl/dwnlds/llvm/3.8/prebuilt/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang++ 
-I../github/libflatarray -I../github/libflatarray/include 
-DHAVE_LIBFLATARRAY -O0 -std=c++14 -o 
/tmp/build/clangxx3_8_pkg/clang/struct_of_arrays/work/soa_compare.benchmark.optim0.exe 
soa_compare.benchmark.cpp
In file included from soa_compare.benchmark.cpp:51:
In file included from 
../github/libflatarray/include/libflatarray/flat_array.hpp:20:
In file included from 
../github/libflatarray/include/libflatarray/estimate_optimum_short_vec_type.hpp:11:
In file included from 
../github/libflatarray/include/libflatarray/detail/streaming_short_vec_switch.hpp:11:
In file included from 
../github/libflatarray/include/libflatarray/short_vec.hpp:244:
../github/libflatarray/include/libflatarray/detail/short_vec_sse_float_16.hpp:460:16: 
error: always_inline function
       '_mm_blendv_ps' requires target feature 'ssse3', but would be 
inlined into function 'blend' that is compiled
       without support for 'ssse3'
         val1 = _mm_blendv_ps(val1, other.val1, mask.val1);
                ^

I've no idea wat to make of the error message :(

I've git pushed a new version of the benchmark.  Maybe you
could try it.  I changed the frames value to get a reasonable
amount of compile time.

-regards,
Larry

**Comment by gentryx** [comment]
Oh. Oh!

Looks like a blunder on my side. _mm_blendv_ps apparently requires SSE3 (according to clang) or SSE 4.1 (according to https://software.intel.com/sites/landingpage/IntrinsicsGuide/#expand=405,414&techs=SSE,SSE2,SSE3,SSSE3,SSE4_1,SSE4_2&text=blendv ). So for CPUs that are limited to SSE, SSE2 my code won't work.

Apparently I don't have any SSE2-only node in my build rotation so I didn't hit this problem before. Will fix. Thanks for debugging!

**Comment by gentryx** [comment]
@cppljevans I've just pushed a commit that adds an alternative code path for blend() which uses SSE2-only code. Could you pull that changeset and test if it's fixing the bug you reported?

Thanks!

**Comment by cppljevans** [comment]
On 10/26/2016 06:17 AM, Andreas Schäfer wrote:
> @cppljevans <https://github.com/cppljevans> I've just pushed a commit
> that adds an alternative code path for blend() which uses SSE2-only
> code. Could you pull that changeset and test if it's fixing the bug you
> reported?
>
> Thanks!
>
Yes.  Fixed:

cmake 
/home/evansl/prog_dev/clang/struct_of_arrays/github/libflatarray.clone/libflatarray
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test SUPPORTS_MARCH_NATIVE
.
.
.

[100%] Linking CXX executable performance_tests
make[3]: Leaving directory 
'/home/evansl/prog_dev/clang/struct_of_arrays/github/libflatarray.clone'
[100%] Built target performance_tests
make[2]: Leaving directory 
'/home/evansl/prog_dev/clang/struct_of_arrays/github/libflatarray.clone'
make[1]: Leaving directory 
'/home/evansl/prog_dev/clang/struct_of_arrays/github/libflatarray.clone'

Compilation finished at Wed Oct 26 06:42:35

Thanks.

**Comment by gentryx** [comment]
Thanks for the update. Please let me know if you run into any further issues.
