### ISSUE TITLE
Vector test of NEON or VFP?

### ISSUE THREAD

**Issue by cicku** [gentryx/libflatarray#2]
I think this library needs to be ported to ARM arch. As 0.2.0 failed to build from source.

https://kojipkgs.fedoraproject.org//work/tasks/4820/8904820/build.log

Thoughts?

**Comment by gentryx** [comment]
I'll need a couple of days to dig up an ARM node where I can develop/test the missing intrinsics.

**Comment by gentryx** [comment]
Fixed in 5e8003c9892f78750df35d68e677b3a149cb3ef2
